before:
  hooks:
    - go mod download
builds:
-
  main: cmd/gomerge/main.go
  ldflags:
    - -s -w
    - -X main.Version={{ .Version }}
    - -X main.Build={{ .Commit }}
    - -X main.BuildDate={{ .Date }}
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - arm
    - arm64
    - 386
archives:
-
  id: gomerge
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^typo|TYPO'
    - typo
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*FEAT|WATCHER|CLI|EVENT|UTILS|CMD[(\\w)]*:+.*$"
      order: 0
    - title: 'Fixes'
      order: 10
      regexp: "^.*FIX|CHORE|BUGFIX|EXAMPLES|BUG[(\\w)]*:+.*$"
    - title: 'Workflow Updates'
      regexp: "^.*ACTIONS|ACTION[(\\w)]*:+.*$"
      order: 20
    - title: 'Other things'
      order: 999
nfpms:
-
  maintainer: 'cian@ciangallagher.net'
  vendor: Cian911
  formats:
    - deb
    - rpm
brews:
  - repository:
      owner: Cian911
      name: homebrew-gomerge
    folder: Formula
    homepage: https://github.com/Cian911/gomerge
    description: |
      Gomerge is a tool to quickly merge several pull requests from your terminal. The intention of this tool is to simplfy, and eventually automate the merging of github pull requests. This tool should be able to run on most systems.
