name: Test

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
    paths:
    - "pkg/**"
    - "cmd/**"
    - "go.*"
    - ".github/workflows/test.yml"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup
      uses: actions/setup-go@v2
      with:
        go-version: '~1.19'
    - name: Install Dependencies
      run: |
        go get github.com/rakyll/gotest
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest
          skip-cache: true
          args: --fix 

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
    - name: Test
      run: |
        make test-all
