name: Test

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
    paths:
    - "pkg/**"
    - "cmd/**"
    - "go.*"
    - ".github/workflows/test.yml"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup
      uses: actions/setup-go@v3.0.0
      with:
        go-version: '~1.18'
    - name: Install Dependencies
      run: |
        export PATH=$PATH:/usr/local/go/bin
        go get github.com/rakyll/gotest
    - name: Test
      run: |
        make test-all
